version: "3.9"
services:
  app-ui:
    image: jrs-frontend
    container_name: application-ui
    build: ./jewelry-rent-system-front
    volumes:
      - './jewelry-rent-system-front:/app'
      - '/app/node_modules'
    ports:
      - 4200:4200
    depends_on: 
      - app-api

  app-api:
    image: jrs-backend
    container_name: application-api
    build: ./jewelry-rent-system
    ports:
      - 8080:8080
    depends_on: 
      - mysql

  adminer:
    image: adminer
    container_name: database-management
    ports:
      - 4201:8080
    depends_on: 
      - mysql

  mysql:
    image: mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: jrs-server
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: jewelry-rent-system
      MYSQL_ROOT_PASSWORD: root