version: "3.9"
services:
  web:
    container_name: web
    build: ./jewelry-rent-system-front
    volumes:
      - './jewelry-rent-system-front:/app'
      - '/app/node_modules'
    ports:
      - 4200:4200
    depends_on: 
      - server

  server:
    container_name: server
    build: ./jewelry-rent-system
    ports:
      - 8080:8080
    depends_on: 
      - mysql

  phpmyadmin:
    container_name: db-admin
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on: 
      - mysql

  mysql:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: jrs-server
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: jewelry-rent-system
      MYSQL_ROOT_PASSWORD: root